// Device command index (SSH-COMMAND-INDEX-COMPLETION-PLAN §2.B, P1).
//
// "What can I run on *this* machine" is a question the local history can never
// answer: a fresh SSH session has no history, and the box may have `kubectl`
// installed and never been typed into. So the app enumerates the device's
// commands once (and re-enumerates on a schedule) and keeps them keyed by host
// fingerprint, feeding them to the ghost completion as low-weight candidates.
//
// Everything here is deliberately split in two: the scripts are generated by
// pure functions and the output is read by a pure parser, so both are testable
// without a shell. Only `collect_*` below touches a session.

use tauri::Emitter;

use crate::db;

/// Cap on one device's index. `compgen -c` on a desktop Linux box returns well
/// over 10 000 names, most of them noise the user will never type; the transport
/// (a single exec's stdout) and the candidate list both stay comfortable here.
pub const COMMAND_ENUM_LIMIT: usize = 5000;

/// How old an index may get before the app re-collects it in the background
/// (decision ③: first connection collects, then refresh at most this often).
pub const INDEX_MAX_AGE_DAYS: i64 = 7;

/// Source labels stored in `host_commands.sources`. Kept to three because the
/// distinction that matters for ranking is "a binary on PATH" vs "something the
/// shell itself provides" vs "something the user defined".
pub const SRC_PATH: &str = "path";
pub const SRC_BUILTIN: &str = "builtin";
pub const SRC_ALIAS: &str = "alias";

/// The POSIX enumeration script (SSH sessions, and WSL distros through
/// `wsl.exe`). Every section is independently guarded, because the whole point is
/// to work on a busybox/ash router as well as on a full bash login shell.
///
/// Two non-obvious pieces:
///  - the zsh line is inside `eval`, not inline. The wrapper runs `bash -lc`
///    first and falls back to `sh -c`, and `sh` parses the *entire* compound
///    before running any of it — an inline `${(k)commands}` is a bad-substitution
///    fatal error in dash even inside a branch it will never take.
///  - the `$PATH` scan is the floor, not a duplicate of `compgen`. Where
///    `compgen` does not exist (ash, csh, a minimal container) it is the only
///    thing that produces anything, which is why it runs unconditionally.
pub fn posix_enum_script() -> String {
  format!(
    r#"{{ \
 [ -n "${{BASH_VERSION:-}}" ] && {{ compgen -c 2>/dev/null | sed 's#^#{SRC_PATH}\t#'; compgen -b 2>/dev/null | sed 's#^#{SRC_BUILTIN}\t#'; }}; \
 [ -n "${{ZSH_VERSION:-}}" ] && eval 'print -rl -- ${{(k)commands}}' 2>/dev/null | sed 's#^#{SRC_PATH}\t#'; \
 alias 2>/dev/null | sed -n 's/^alias \([^=]*\)=.*/\1/p' | sed 's#^#{SRC_ALIAS}\t#'; \
 if [ -n "${{PATH:-}}" ]; then _wrolp_ifs=$IFS; IFS=:; for _wrolp_d in $PATH; do \
 [ -d "$_wrolp_d" ] && ls -1 "$_wrolp_d" 2>/dev/null | sed "s#^#{SRC_PATH}\t#"; done; IFS=$_wrolp_ifs; fi; \
}} 2>/dev/null | sort -u | head -n {COMMAND_ENUM_LIMIT}"#
  )
}

/// The Windows PowerShell enumeration script (a local shell tab that is not WSL).
///
/// `Get-Command -All` alone is not used because its `-All` also returns every
/// hidden duplicate of the same executable, which is pure index bloat. The
/// `.exe` suffix is dropped because that is what a user types: `git`, not
/// `git.exe` — both work, and the shorter form is the one that matches history.
pub fn powershell_enum_script() -> String {
  format!(
    "$ErrorActionPreference='SilentlyContinue'; \
$paths = Get-Command -CommandType Application,ExternalScript | ForEach-Object {{ \"{SRC_PATH}\" + \"`t\" + ($_.Name -replace '\\.exe$','') }}; \
$aliases = Get-Command -CommandType Alias | ForEach-Object {{ \"{SRC_ALIAS}\" + \"`t\" + $_.Name }}; \
$builtins = Get-Command -CommandType Function,Cmdlet | ForEach-Object {{ \"{SRC_BUILTIN}\" + \"`t\" + $_.Name }}; \
@($paths) + @($aliases) + @($builtins) | Sort-Object -Unique | Select-Object -First {COMMAND_ENUM_LIMIT}"
  )
}

/// The row type the frontend reads. Defined with the other DB row shapes
/// (`crate::db::HostCommandDto`) so a fresh collection and a SQLite read return
/// byte-identical JSON.
pub use crate::db::HostCommandDto;

/// Which *local* process runs the enumeration. An SSH session is not a route: it
/// execs on its own live handle in `collect_for_tab`, because spawning a new SSH
/// connection just to list commands would re-authenticate against the server for
/// every refresh.
pub enum EnumRoute {
  /// A WSL distro: `wsl.exe [-d <distro>] -- sh -lc <POSIX script>`. A distro is
  /// its own device precisely because its `$PATH` is its own. `None` means the
  /// tab was opened without naming one, so the *system default* distro is what we
  /// are actually sitting in — passing `-d default` would fail, because that is a
  /// label of ours, not a distro.
  Wsl(Option<String>),
  /// A local Windows shell, enumerated through PowerShell (there is no POSIX
  /// layer to `compgen` against here).
  #[cfg(windows)]
  LocalWindows,
  /// A local POSIX shell running natively.
  #[cfg(not(windows))]
  LocalPosix,
}

impl EnumRoute {
  pub fn script(&self) -> String {
    match self {
      EnumRoute::Wsl(_) => posix_enum_script(),
      #[cfg(windows)]
      EnumRoute::LocalWindows => powershell_enum_script(),
      #[cfg(not(windows))]
      EnumRoute::LocalPosix => posix_enum_script(),
    }
  }
}

/// How long to wait for a just-opened SSH session to publish its handle (×500 ms).
/// The connect task stores the handle a few hundred milliseconds after the shell
/// starts, which is exactly when the first auto-collection runs.
pub const HANDLE_WAIT_TRIES: u32 = 20;

/// How long to wait for one collection before giving up. Generous on purpose: a
/// 5 000-line `compgen` over a laggy link is slow, and a collection that gives up
/// costs only the convenience of completion — never the session.
pub const COLLECT_TIMEOUT_SECS: u64 = 20;

/// Run a non-SSH route and return its raw stdout.
pub async fn run_enum(route: &EnumRoute) -> Result<String, String> {
  let script = route.script();
  let work = async {
    match route {
      EnumRoute::Wsl(distro) => {
        // A local shell tab: run the same script through `wsl.exe`. With no distro
        // named, the system default is the one this tab is sitting in, so `-d` has
        // to be left off entirely rather than fed our own `default` label.
        let mut args: Vec<String> = Vec::new();
        if let Some(d) = distro {
          args.extend(["-d".to_string(), d.clone()]);
        }
        args.extend([
          "--".to_string(),
          "sh".to_string(),
          "-lc".to_string(),
          script,
        ]);
        let out = tokio::process::Command::new("wsl.exe")
          .args(&args)
          .output()
          .await
          .map_err(|e| format!("wsl.exe failed: {e}"))?;
        Ok(decode_child_output(&out))
      }
      #[cfg(windows)]
      EnumRoute::LocalWindows => {
        let out = tokio::process::Command::new("powershell.exe")
          .args(["-NoProfile", "-NonInteractive", "-Command", &script])
          .output()
          .await
          .map_err(|e| format!("powershell.exe failed: {e}"))?;
        Ok(decode_child_output(&out))
      }
      #[cfg(not(windows))]
      EnumRoute::LocalPosix => {
        let out = tokio::process::Command::new("/bin/sh")
          .args(["-lc", &script])
          .output()
          .await
          .map_err(|e| format!("sh failed: {e}"))?;
        Ok(decode_child_output(&out))
      }
    }
  };
  match tokio::time::timeout(std::time::Duration::from_secs(COLLECT_TIMEOUT_SECS), work).await {
    Ok(r) => r,
    Err(_) => Err(format!(
      "command enumeration timed out after {COLLECT_TIMEOUT_SECS}s"
    )),
  }
}

/// Child-process stdout. A failed `powershell.exe` still prints to stderr, and an
/// unknown distro fails from `wsl.exe` — neither may panic, and anything that is
/// not valid UTF-8 comes back as whatever `lossy` gives. An empty result is then
/// silently ignored by the caller, which is the designed behaviour for a device we
/// cannot enumerate (plan §4, row 1).
fn decode_child_output(out: &std::process::Output) -> String {
  if !out.status.success() {
    eprintln!(
      "[host_commands] enumerator exited {}: {}",
      out.status.code().unwrap_or(-1),
      String::from_utf8_lossy(&out.stderr).trim()
    );
  }
  String::from_utf8_lossy(&out.stdout).to_string()
}

/// Whether a device's index is missing or old enough to be worth re-collecting
/// (decision ③: collect on first sighting, then at most this often — never on
/// every connect, which is what would make a slow box feel broken).
///
/// `info` is the device's `(rows, newest collected_at)` as stored, and `cleared_at`
/// is when the user cleared it. A clear counts as "known and answered": re-learning
/// the box on the next connect would turn the act of forgetting into a no-op nobody
/// could see the end of, so collection stays off until something newer than the
/// clear happens — which a manual refresh does by stamping a fresh `collected_at`
/// (and resetting the marker) in `replace_host_commands`.
pub fn needs_collection(info: Option<(i64, i64)>, cleared_at: i64, now_ms: i64) -> bool {
  let day_ms = 86_400_000i64;
  if cleared_at > 0 {
    return info.is_some_and(|(_, at)| at > cleared_at);
  }
  match info {
    None => true,
    Some((_, 0)) => true,
    Some((_, at)) => now_ms.saturating_sub(at) > INDEX_MAX_AGE_DAYS * day_ms,
  }
}

/// Collect a tab's device index and store it under `fingerprint`. Returns the
/// number of commands indexed; `Ok(0)` means the device gave us nothing readable,
/// which is reported as success because there is nothing to fix.
///
/// `kind` is the device kind from `host-identified` (`ssh` / `wsl` / `local` / …).
/// The SSH route is still resolved by looking for a live handle rather than by
/// trusting `kind`, because a handle that has not come up yet must not be
/// enumerated through the local machine by accident — but the *local* split
/// (WSL vs native) is decided by `kind` alone: a WSL tab with no named distro has
/// nothing to distinguish it from a PowerShell tab otherwise, and would end up
/// indexed with the wrong command set.
pub async fn collect_for_tab(
  app: &tauri::AppHandle,
  tab_id: u32,
  fingerprint: &str,
  kind: &str,
  distro: Option<&str>,
) -> Result<usize, String> {
  use tauri::Manager;
  let state = app.state::<crate::ssh_session::AppState>();
  // `connect` stores the session handle from its own task, so there is a brief
  // window after the shell comes up where the handle exists but is not yet
  // reachable. Wait through it rather than letting the first auto-collection of a
  // device be the one that fails.
  let mut handle = None;
  if kind == "ssh" {
    for attempt in 0..HANDLE_WAIT_TRIES {
      match crate::remote_fs::get_jump_handle(&state, tab_id) {
        Ok(h) => {
          handle = Some(h);
          break;
        }
        Err(e) => {
          if attempt + 1 == HANDLE_WAIT_TRIES {
            return Err(format!("no SSH session to enumerate on tab {tab_id}: {e}"));
          }
          tokio::time::sleep(std::time::Duration::from_millis(500)).await;
        }
      }
    }
  }
  let raw = match handle {
    Some(handle) => {
      let script = posix_enum_script();
      let work = async move { crate::host_analysis::exec_on_handle(&handle, &script).await };
      match tokio::time::timeout(std::time::Duration::from_secs(COLLECT_TIMEOUT_SECS), work).await {
        Ok(r) => r?,
        Err(_) => {
          return Err(format!(
            "remote enumeration timed out after {COLLECT_TIMEOUT_SECS}s"
          ))
        }
      }
    }
    None => {
      // Only non-SSH kinds reach here (the SSH branch above returns on failure):
      // never enumerate the local machine on behalf of a remote device, or an index
      // of the user's own commands gets filed under a server's fingerprint and
      // starts suggesting binaries that box does not have.
      let route = if kind == "wsl" {
        EnumRoute::Wsl(
          distro
            .filter(|d| !d.trim().is_empty() && *d != "default")
            .map(|d| d.to_string()),
        )
      } else {
        #[cfg(windows)]
        {
          EnumRoute::LocalWindows
        }
        #[cfg(not(windows))]
        {
          EnumRoute::LocalPosix
        }
      };
      run_enum(&route)
        .await
        .map_err(|err| format!("{kind} enumeration failed on tab {tab_id}: {err}"))?
    }
  };

  let rows = parse_command_enum(&raw);
  if rows.is_empty() {
    eprintln!("[host_commands] nothing enumerated for {fingerprint} (leaving the index as is)");
    return Ok(0);
  }
  let now_ms = chrono::Utc::now().timestamp_millis();
  let db = state.db.clone();
  let fp = fingerprint.to_string();
  let stored = tokio::task::spawn_blocking(move || {
    let mut conn = db.lock().map_err(|e| e.to_string())?;
    db::replace_host_commands(&mut conn, &fp, &rows, now_ms)
  })
  .await
  .map_err(|e| e.to_string())??;

  let _ = app.emit(
    "host-commands-updated",
    serde_json::json!({ "fingerprint": fingerprint, "count": stored }),
  );
  Ok(stored)
}

/// Decision ③'s gate, wrapped around `collect_for_tab` for the two places that
/// auto-collect. Errors are logged and swallowed: completion suggestion is the last
/// thing a connection should be judged on.
pub async fn maybe_collect(
  app: &tauri::AppHandle,
  tab_id: u32,
  fingerprint: &str,
  kind: &str,
  distro: Option<&str>,
) {
  use tauri::Manager;
  // Clone the Arc out and drop the `State` guard immediately: the age check below
  // awaits, and a borrowed state would pin `app` across it for nothing.
  let db = app.state::<crate::ssh_session::AppState>().db.clone();
  let (info, cleared_at) = match db.lock() {
    Ok(conn) => (
      db::host_index_info(&conn, fingerprint).ok().flatten(),
      db::host_commands_cleared_at(&conn, fingerprint).unwrap_or(0),
    ),
    Err(_) => (None, 0),
  };
  let now_ms = chrono::Utc::now().timestamp_millis();
  if !needs_collection(info, cleared_at, now_ms) {
    return;
  }
  if let Err(e) = collect_for_tab(app, tab_id, fingerprint, kind, distro).await {
    eprintln!("[host_commands] auto-collection failed for tab={tab_id}: {e}");
  }
}

/// Parse the scripts' `source\tname` output into `(name, csv-sources)` pairs.
///
/// The parser owns the rules the scripts cannot enforce themselves:
///  - a name with whitespace or a control character is dropped: it could never be
///    appended to an input line safely (the ghost pool types what it is given);
///  - a line with no tab is treated as an unlabeled name, which is what a shell
///    that swallowed our `sed` produces, and is the least wrong guess;
///  - sources for the same name merge (order: path, builtin, alias) so `cd`
///    appearing as both a builtin and a directory-listing binary is one row;
///  - output is capped at `COMMAND_ENUM_LIMIT` *after* merging, so the cap applies
///    to what actually lands in the index rather than to raw script lines.
pub fn parse_command_enum(stdout: &str) -> Vec<(String, String)> {
  const ORDER: [&str; 3] = [SRC_PATH, SRC_BUILTIN, SRC_ALIAS];
  let mut merged: Vec<(String, Vec<String>)> = Vec::new();
  let mut index: std::collections::HashMap<String, usize> = std::collections::HashMap::new();

  for line in stdout.lines() {
    let line = line.trim_end_matches('\r');
    if line.trim().is_empty() {
      continue;
    }
    let (source, name) = match line.split_once('\t') {
      Some((head, tail)) => {
        let head = head.trim();
        let name = tail.trim();
        if !matches!(head, SRC_PATH | SRC_BUILTIN | SRC_ALIAS) {
          // Not one of our labels: the tab came from unrelated output (a banner,
          // a `key=value` line), so the whole line is the candidate name instead.
          (SRC_PATH, line.trim())
        } else {
          (head, name)
        }
      }
      None => (SRC_PATH, line.trim()),
    };
    if !looks_like_command(name) {
      continue;
    }
    match index.get(name) {
      Some(&at) => {
        let entry = &mut merged[at].1;
        if !entry.iter().any(|s| s == source) {
          entry.push(source.to_string());
        }
      }
      None => {
        index.insert(name.to_string(), merged.len());
        merged.push((name.to_string(), vec![source.to_string()]));
      }
    }
  }

  let mut out: Vec<(String, String)> = merged
    .into_iter()
    .map(|(name, sources)| {
      let mut sorted = sources;
      sorted.sort_by_key(|s| ORDER.iter().position(|o| o == s).unwrap_or(ORDER.len()));
      (name, sorted.join(","))
    })
    .collect();
  out.truncate(COMMAND_ENUM_LIMIT);
  out
}

/// Whether `name` can be typed into a shell as one word.
fn looks_like_command(name: &str) -> bool {
  !name.is_empty()
    && name.len() <= 128
    && !name.chars().any(|c| c.is_whitespace() || c.is_control())
    // Quoting artefacts of the shells we parse (zsh prints `x=y` for some
    // parameter expansions; a leading quote means the line was never a name).
    && !name.starts_with('\'')
    && !name.starts_with('"')
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn posix_script_guards_every_section() {
    let s = posix_enum_script();
    // The three independent sources must each be reachable on a shell that lacks
    // the others, which is what the plan's busybox self-check item is about.
    assert!(s.contains("BASH_VERSION"));
    assert!(s.contains("ZSH_VERSION"));
    assert!(s.contains("compgen -c"));
    assert!(s.contains("compgen -b"));
    assert!(s.contains("for _wrolp_d in $PATH"));
    assert!(s.contains(&format!("head -n {COMMAND_ENUM_LIMIT}")));
    // zsh's parameter-expansion syntax may only appear inside `eval`, or dash
    // fails the whole script at parse time.
    let without_eval = s.replace("eval ", "");
    assert!(
      without_eval.matches("${(k)commands}").count() <= 1,
      "the zsh-only expansion must stay inside the eval'd string"
    );
  }

  #[test]
  fn powershell_script_labels_and_strips_exe() {
    let s = powershell_enum_script();
    assert!(s.contains("-replace '\\.exe$'"));
    assert!(s.contains("Get-Command -CommandType Application,ExternalScript"));
    assert!(s.contains("Select-Object -First 5000"));
  }

  #[test]
  fn parses_labeled_lines_into_one_row_per_name() {
    let rows = parse_command_enum("path\tgit\nbuiltin\tcd\npath\tcd\n");
    assert_eq!(
      rows,
      vec![
        ("git".to_string(), "path".to_string()),
        // Same name from two sources: one row, sources ordered path → builtin.
        ("cd".to_string(), "path,builtin".to_string()),
      ]
    );
  }

  #[test]
  fn tolerates_unlabeled_and_blank_output() {
    // ash/busybox with `sed` unavailable, plus the empty-result case that must
    // stay silent rather than error.
    let rows = parse_command_enum("ls\n\n\r\n  \n/usr/bin; done\n");
    assert_eq!(rows, vec![("ls".to_string(), "path".to_string())]);
    assert_eq!(parse_command_enum(""), Vec::new());
    assert_eq!(parse_command_enum("bash: compgen: not found\n"), Vec::new());
  }

  #[test]
  fn drops_anything_that_could_not_be_typed_as_one_word() {
    let rows = parse_command_enum(
      "path\ttwo words\npath\tbad\u{7}name\n\tleading tab\nalias\tx=y\npath\tok-1.2\n",
    );
    let names: Vec<&str> = rows.iter().map(|(n, _)| n.as_str()).collect();
    // Two words, an embedded control byte and a stray tab-separated banner all go;
    // ordinary punctuation in a name (`x=y`, `ok-1.2`) stays, because shells really
    // do have such commands and the pool has to be able to offer them.
    assert_eq!(names, vec!["x=y", "ok-1.2"], "got {rows:?}");
  }

  #[test]
  fn caps_at_the_index_limit_after_merging() {
    let mut lines = String::new();
    for i in 0..COMMAND_ENUM_LIMIT + 500 {
      lines.push_str(&format!("path\tcmd{i}\n"));
    }
    assert_eq!(parse_command_enum(&lines).len(), COMMAND_ENUM_LIMIT);
  }

  #[test]
  fn a_name_repeated_from_the_same_source_merges_into_one_row() {
    // `$PATH` scanned twice (a duplicated directory) must not double-count.
    let rows = parse_command_enum("path\tdocker\npath\tdocker\n");
    assert_eq!(rows, vec![("docker".to_string(), "path".to_string())]);
  }

  #[test]
  fn a_missing_or_ancient_index_is_collected_and_a_fresh_one_is_not() {
    let day = 86_400_000i64;
    let now = 1_760_000_000_000;
    assert!(needs_collection(None, 0, now), "never collected");
    assert!(
      needs_collection(Some((120, 0)), 0, now),
      "a row with no timestamp is treated as unknown"
    );
    assert!(
      needs_collection(Some((120, now - 8 * day)), 0, now),
      "8 days old"
    );
    assert!(
      !needs_collection(Some((120, now - 6 * day)), 0, now),
      "6 days old is recent enough — the whole point is not to do this on every connect"
    );
    assert!(
      !needs_collection(Some((120, now - INDEX_MAX_AGE_DAYS * day)), 0, now),
      "exactly at the limit is still valid; the next connect crosses it"
    );
    // Note: `host_index_info` reports an empty index as `None`, so the row count
    // here is never 0 in practice — only the age is read.
  }

  #[test]
  fn a_cleared_index_stays_cleared_until_something_relearns_it() {
    let day = 86_400_000i64;
    let now = 1_760_000_000_000;
    // The case that makes "clear" mean anything: the index is now empty, and
    // reconnecting is exactly the moment an auto-collect would fire.
    assert!(!needs_collection(None, now, now), "cleared moments ago");
    assert!(
      !needs_collection(Some((120, now - 30 * day)), now - day, now),
      "an index older than the clear cannot resurrect it"
    );
    assert!(
      needs_collection(Some((120, now)), now - day, now),
      "a collection newer than the clear is a deliberate re-learn"
    );
    // The clear never expires on its own, by design: it is an explicit act of
    // forgetting, and only the explicit act of collecting again (which stamps a
    // newer `collected_at`) lifts it. An auto-collect resurrecting the list a week
    // later would be the same surprise one day later.
  }
}
